---
- name: Install and Configure Grafana Enterprise via Yandex Pool DEB
  hosts: grafana_host
  become: yes
  vars_files:
    - secrets.yml
  vars:
    local_host: "127.0.0.1"
    grafana_port: "3000"
    grafana_url: "http://{{ local_host }}:{{ grafana_port }}"
    api_ds: "/api/datasources"
    api_pwd: "/api/user/password"
    api_import: "/api/dashboards/import"
    
    prefix_net: "https://"
    host_mirror: "mirror.yandex.ru"
    mid_folder: "/mirrors/"
    dom_part1: "packages."
    dom_part2: "grafana."
    dom_part3: "com"
    tail_path: "/enterprise/deb/pool/main/g/grafana-enterprise"
    file_deb: "/grafana-enterprise_10.2.3_amd64.deb"
    grafana_download_url: "{{ [prefix_net, host_mirror, mid_folder, dom_part1, dom_part2, dom_part3, tail_path, file_deb] | join('') }}"
    
    g_proto: "https://"
    g_domain: "grafana.com"
    g_api_base: "/api/dashboards"
    dash_1860_tail: "/1860/revisions/37/download"
    dash_12708_tail: "/12708/revisions/1/download"
    url_dash_1860: "{{ [g_proto, g_domain, g_api_base, dash_1860_tail] | join('') }}"
    url_dash_12708: "{{ [g_proto, g_domain, g_api_base, dash_12708_tail] | join('') }}"
  tasks:
    - name: Udalenie starih repozitoriev Grafana
      file:
        path: /etc/apt/sources.list.d/grafana.list
        state: absent
    - name: Ustanovka neobhodimih zavisimostei
      apt:
        name: [apt-transport-https, wget, adduser, libfontconfig1, musl, curl, jq]
        state: present
        update_cache: yes
    - name: Skachivanie paketa Grafana s zerkala Yandeksa
      get_url:
        url: "{{ grafana_download_url }}"
        dest: /tmp/grafana-enterprise.deb
        mode: '0644'
    - name: Lokalnaya ustanovka Grafana Enterprise iz DEB
      apt:
        deb: /tmp/grafana-enterprise.deb
        state: present
    - name: Start and enable Grafana service daemon
      systemd:
        name: grafana-server
        state: restarted
        enabled: yes
    - name: Wait for Grafana port to be fully ready
      wait_for:
        port: 3000
        timeout: 45
    - name: Change default admin password to secure coursework version
      uri:
        url: "{{ grafana_url }}{{ api_pwd }}"
        method: PUT
        user: "admin"
        password: "admin"
        force_basic_auth: yes
        status_code: [200, 270, 401]
        body_format: json
        body:
          oldPassword: "admin"
          newPassword: "{{ grafana_admin_password }}"
          confirmNew: "{{ grafana_admin_password }}"
    - name: Configure Prometheus Data Source via REST API
      uri:
        url: "{{ grafana_url }}{{ api_ds }}"
        method: POST
        user: "admin"
        password: "{{ grafana_admin_password }}"
        force_basic_auth: yes
        status_code: [200, 201, 409]
        body_format: json
        body:
          name: "prometheus"
          type: "prometheus"
          access: "proxy"
          url: "http://{{ hostvars[groups['prometheus_host'] | first]['ansible_host'] }}:9090"
          isDefault: true
    - name: Download Linux Node Exporter dashboard JSON model from official API
      get_url:
        url: "{{ url_dash_1860 }}"
        dest: "/tmp/dashboard_1860.json"
        mode: '0644'
        decompress: no
    - name: Download Nginx Exporter dashboard JSON model from official API
      get_url:
        url: "{{ url_dash_12708 }}"
        dest: "/tmp/dashboard_12708.json"
        mode: '0644'
        decompress: no
    - name: Patch dashboard 1860 JSON to enforce valid datasource name
      replace:
        path: "/tmp/dashboard_1860.json"
        regexp: '\$\{DS_PROMETHEUS\}'
        replace: 'prometheus'
    - name: Patch dashboard 12708 JSON to enforce valid datasource name
      replace:
        path: "/tmp/dashboard_12708.json"
        regexp: '\$\{DS_PROMETHEUS\}'
        replace: 'prometheus'
    - name: Enforce job name alignment for Node Exporter to match Prometheus Targets
      replace:
        path: "/tmp/dashboard_1860.json"
        regexp: 'job="node_exporter"'
        replace: 'job="node"'
    - name: Enforce job name alignment for Nginx Exporter to match Prometheus Targets
      replace:
        path: "/tmp/dashboard_12708.json"
        regexp: 'job="nginx_exporter"'
        replace: 'job="nginx-exporter"'
    - name: Read dashboard 1860 from remote target disk
      slurp:
        src: "/tmp/dashboard_1860.json"
      register: remote_json_1860
    - name: Read dashboard 12708 from remote target disk
      slurp:
        src: "/tmp/dashboard_12708.json"
      register: remote_json_12708
    - name: Import Full Linux Node Exporter Dashboard via REST API
      uri:
        url: "{{ grafana_url }}{{ api_import }}"
        method: POST
        user: "admin"
        password: "{{ grafana_admin_password }}"
        force_basic_auth: yes
        status_code: [200, 201, 409]
        body_format: json
        body:
          dashboard: "{{ remote_json_1860.content | b64decode | from_json }}"
          overwrite: true
          inputs:
            - name: "DS_PROMETHEUS"
              pluginId: "prometheus"
              type: "datasource"
              value: "prometheus"
    - name: Import Full Nginx Exporter Dashboard via REST API
      uri:
        url: "{{ grafana_url }}{{ api_import }}"
        method: POST
        user: "admin"
        password: "{{ grafana_admin_password }}"
        force_basic_auth: yes
        status_code: [200, 201, 409]
        body_format: json
        body:
          dashboard: "{{ remote_json_12708.content | b64decode | from_json }}"
          overwrite: true
          inputs:
            - name: "DS_PROMETHEUS"
              pluginId: "prometheus"
              type: "datasource"
              value: "prometheus"