---
- name: Deploy and configure Prometheus Server on Debian 13
  hosts: prometheus_host
  become: yes
  tasks:
    - name: Ustanovka paketa Prometheus iz repo Debian
      apt:
        name: prometheus
        state: latest
        update_cache: yes

    - name: Generaciya динамического файла конфигурации prometheus.yml
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            # 1. Сбор метрик железа виртуальных машин
            - job_name: 'node'
              static_configs:
                - targets:
          {% for host in groups['webservers'] %}
                  - '{{ hostvars[host]["ansible_host"] }}:9100'
          {% endfor %}
              relabel_configs:
          {% for host in groups['webservers'] %}
                - source_labels: [__address__]
                  regex: '{{ hostvars[host]["ansible_host"] }}:.*'
                  target_label: instance
                  replacement: '{{ hostvars[host]["ansible_host"] }} ({{ host }})'
          {% endfor %}

            # 2. Сбор метрик веб-сервера Nginx
            - job_name: 'nginx-exporter'
              static_configs:
                - targets:
          {% for host in groups['webservers'] %}
                  - '{{ hostvars[host]["ansible_host"] }}:9113'
          {% endfor %}
              relabel_configs:
          {% for host in groups['webservers'] %}
                - source_labels: [__address__]
                  regex: '{{ hostvars[host]["ansible_host"] }}:.*'
                  target_label: instance
                  replacement: '{{ hostvars[host]["ansible_host"] }} ({{ host }})'
          {% endfor %}

    - name: Zapusk sluzhby Prometheus i dobavlenie v avtozagruzku
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
