[bastion]
bastion_host ansible_host=158.160.49.193 ansible_user=debian

[webservers]
web1 ansible_host=10.0.10.34 ansible_user=debian
web2 ansible_host=10.0.20.27 ansible_user=debian

[logging_storage]
elasticsearch_server ansible_host=10.0.10.4 ansible_user=debian

[prometheus_host]
prometheus_server ansible_host=10.0.10.6 ansible_user=debian

[grafana_host]
grafana_server ansible_host=10.0.1.24 ansible_user=debian

[kibana_host]
kibana_server ansible_host=10.0.1.20 ansible_user=debian

[all:vars]
ansible_user=debian
ansible_ssh_private_key_file=/home/user/.ssh/id_rsa
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=debian@158.160.49.193"

[bastion:vars]
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
