[bastion]
bastion_host ansible_host=89.169.138.100 ansible_user=debian

[webservers]
web1 ansible_host=10.0.10.17 ansible_user=debian
web2 ansible_host=10.0.20.16 ansible_user=debian

[logging_storage]
elasticsearch_server ansible_host=10.0.10.14 ansible_user=debian

[prometheus_host]
prometheus_server ansible_host=10.0.10.27 ansible_user=debian

[grafana_host]
grafana_server ansible_host=10.0.1.26 ansible_user=debian

[kibana_host]
kibana_server ansible_host=10.0.1.22 ansible_user=debian

[all:vars]
ansible_user=debian
ansible_ssh_private_key_file=/home/user/.ssh/id_rsa
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=debian@89.169.138.100"

[bastion:vars]
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
