---
- name: Развертывание и настройка Elastic Stack 8.11.3 (Бобков А.К.)
  hosts: logging_storage, kibana_host
  become: yes

  vars:
    elastic_jvm_min: "-Xms1g"
    elastic_jvm_max: "-Xmx1g"

    el_proto: "https://"
    el_mirror: "mirror.yandex.ru"
    es_folder: "/mirrors/elastic/8/pool/main/e/elasticsearch/"
    kb_folder: "/mirrors/elastic/8/pool/main/k/kibana/"
    deb_es_file: "elasticsearch-8.11.3-amd64.deb"
    deb_kb_file: "kibana-8.11.3-amd64.deb"

    url_elastic_8113: "{{ [el_proto, el_mirror, es_folder, deb_es_file] | join('') }}"
    url_kibana_8113: "{{ [el_proto, el_mirror, kb_folder, deb_kb_file] | join('') }}"

  tasks:
    # --------------------------------------------------------------------------
    # Подсистема Elasticsearch (Выполняется только на хосте logging_storage)
    # --------------------------------------------------------------------------
    - name: "Elasticsearch: настройка vm.max_map_count"
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes
      when: inventory_hostname in groups['logging_storage']

    - name: "Elasticsearch: установка зависимостей"
      apt:
        name: [apt-transport-https, curl, jq, default-jre]
        state: present
        update_cache: yes
      when: inventory_hostname in groups['logging_storage']

    - name: "Elasticsearch: скачивание пакета"
      get_url:
        url: "{{ url_elastic_8113 }}"
        dest: "/tmp/elasticsearch-8.11.3.deb"
        mode: "0644"
      when: inventory_hostname in groups['logging_storage']

    - name: "Elasticsearch: установка пакета"
      apt:
        deb: "/tmp/elasticsearch-8.11.3.deb"
        state: present
      when: inventory_hostname in groups['logging_storage']

    - name: "Elasticsearch: очистка и установка лимитов JVM"
      lineinfile:
        path: /etc/elasticsearch/jvm.options
        regexp: "^-Xm"
        state: absent
      when: inventory_hostname in groups['logging_storage']

    - name: "Elasticsearch: установка новых лимитов JVM"
      lineinfile:
        path: /etc/elasticsearch/jvm.options
        line: "{{ item }}"
      loop:
        - "{{ elastic_jvm_min }}"
        - "{{ elastic_jvm_max }}"
      when: inventory_hostname in groups['logging_storage']

    - name: "Elasticsearch: полное пересоздание чистого Keystore"
      shell: |
        rm -f /etc/elasticsearch/elasticsearch.keystore
        /usr/share/elasticsearch/bin/elasticsearch-keystore create
      register: keystore_recreate
      failed_when: keystore_recreate.rc != 0
      when: inventory_hostname in groups['logging_storage']

    - name: "Elasticsearch: генерация конфигурации без X-Pack"
      copy:
        dest: /etc/elasticsearch/elasticsearch.yml
        content: |
          cluster.name: coursework-logging-cluster
          node.name: {{ inventory_hostname }}
          path.data: /var/lib/elasticsearch
          path.logs: /var/log/elasticsearch
          network.host: 0.0.0.0
          http.port: 9200
          discovery.type: single-node
          ingest.geoip.downloader.enabled: false
          xpack.security.enabled: false
        owner: root
        group: elasticsearch
        mode: "0660"
      when: inventory_hostname in groups['logging_storage']

    - name: "Elasticsearch: запуск службы"
      systemd:
        name: elasticsearch
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: inventory_hostname in groups['logging_storage']

    # --------------------------------------------------------------------------
    # Подсистема Kibana (Выполняется только на хосте kibana_host!)
    # --------------------------------------------------------------------------

    - name: "Kibana: Ожидание полной готовности API Elasticsearch по внутренней сети"
      uri:
        url: "http://{{ hostvars[groups['logging_storage'] | first]['ansible_host'] }}:9200"
        status_code: 200
        timeout: 5 # Защита: сбрасывать зависший запрос через 5 секунд, если сеть еще не поднялась
      register: es_api_check
      until: es_api_check.status == 200
      retries: 60  # Даем Java-машине до 10 минут на холодный старт в Яндексе
      delay: 10
      when: inventory_hostname in groups['kibana_host']
      become: no # Запрос выполняется от пользователя debian, sudo не требуется


    - name: "Kibana: установка системных зависимостей"
      apt:
        name: [apt-transport-https, curl, jq]
        state: present
      when: inventory_hostname in groups['kibana_host']

    - name: "Kibana: скачивание пакета с зеркала Яндекса"
      get_url:
        url: "{{ url_kibana_8113 }}"
        dest: "/tmp/kibana-8.11.3.deb"
        mode: "0644"
      when: inventory_hostname in groups['kibana_host']

    - name: "Kibana: принудительная установка пакета"
      apt:
        deb: "/tmp/kibana-8.11.3.deb"
        state: present
      when: inventory_hostname in groups['kibana_host']

    - name: "Kibana: создание директории логов"
      file:
        path: "/var/log/kibana"
        owner: kibana
        group: kibana
        state: directory
        mode: "0750"
      when: inventory_hostname in groups['kibana_host']

    - name: "Kibana: генерация конфигурации связи с базой логов"
      copy:
        dest: /etc/kibana/kibana.yml
        content: |
          server.port: 5601
          server.host: "0.0.0.0"
          elasticsearch.hosts: ["http://{{ hostvars[groups['logging_storage'] | first]['ansible_host'] }}:9200"]
          xpack.security.enabled: false
        owner: root
        group: kibana
        mode: "0660"
      when: inventory_hostname in groups['kibana_host']

    - name: "Kibana: запуск и активация службы в systemd"
      systemd:
        name: kibana
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: inventory_hostname in groups['kibana_host']

    - name: "Kibana: ожидание открытия сетевого порта 5601"
      wait_for:
        host: 0.0.0.0
        port: 5601
        timeout: 120
      when: inventory_hostname in groups['kibana_host']
