---
# ==============================================================================
# PROMETHEUS MONITORING SERVER
# ==============================================================================
- name: Deploy and configure Prometheus Server on Debian 13
  hosts: prometheus_host
  become: yes
  tasks:
    - name: Ustanovka paketa Prometheus iz repo Debian
      apt:
        name: prometheus
        state: latest
        update_cache: yes

    - name: Generaciya konfiguracionnogo fajla prometheus.yml
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'node_exporter_metrics'
              static_configs:
                - targets:
          {% for host in groups['webservers'] %}
                  - '{{ hostvars[host]["ansible_host"] }}:9100'
          {% endfor %}
            - job_name: 'nginx_exporter_metrics'
              static_configs:
                - targets:
          {% for host in groups['webservers'] %}
                  - '{{ hostvars[host]["ansible_host"] }}:9113'
          {% endfor %}

    - name: Zapusk sluzhby Prometheus i dobavlenie v avtozagruzku
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
