---
- name: "Шаг 2.1: Развертывание PostgreSQL и pg-adapter"
  hosts: logging_storage
  become: true
  vars_files:
    - secrets.yml
  tasks:
    - name: "Создание директории данных PostgreSQL"
      ansible.builtin.file:
        path: /opt/postgres/data
        state: directory
        mode: "0750" # Безопасные права, Postgres не любит 0777

    - name: "Запуск контейнера PostgreSQL"
      community.docker.docker_container:
        name: postgres-metrics
        image: "postgres:15-alpine"
        restart_policy: always
        network_mode: host
        env:
          POSTGRES_USER: "crunchy_admin"
          POSTGRES_PASSWORD: "{{ postgres_password }}"
          POSTGRES_DB: "postgres"
        volumes:
          - "/opt/postgres/data:/var/lib/postgresql/data"

    - name: "Запуск контейнера pg-adapter (PostgreSQL Exporter)"
      community.docker.docker_container:
        name: pg-adapter
        image: "quay.io/prometheuscommunity/postgres-exporter:v0.15.0"
        restart_policy: always
        network_mode: host
        env:
          # Строка подключения к базе данных с использованием переменной из secrets.yml
          DATA_SOURCE_NAME: "postgresql://crunchy_admin:{{ postgres_password }}@127.0.0.1:5432/postgres?sslmode=disable"

- name: "Шаг 2.2: Развертывание Kibana"
  hosts: kibana_host
  become: true
  tasks:
    - name: "Запуск контейнера Kibana"
      community.docker.docker_container:
        name: kibana
        image: "docker.elastic.co/kibana/kibana:7.17.13"
        restart_policy: always
        network_mode: host
        env:
          # Динамически получаем IP сервера logging_storage
          ELASTICSEARCH_HOSTS: "http://{{ hostvars[groups['logging_storage'] | first]['ansible_host'] }}:9200"

    - name: "Ожидание готовности веб-интерфейса Kibana (порт 5601)"
      ansible.builtin.wait_for:
        port: 5601
        timeout: 90