[bastion]
bastion_host ansible_host=51.250.94.102 ansible_user=debian

[kibana_host]
kibana_server ansible_host=10.100.10.9 ansible_user=debian elastic_target_ip=10.100.20.17

[grafana_host]
grafana_server ansible_host=10.100.10.35 ansible_user=debian postgres_target_ip=10.100.20.17

[logging_storage]
elasticsearch_server ansible_host=10.100.20.17 ansible_user=debian

[web_nodes]
web-node-0 ansible_host=10.100.20.12 ansible_user=debian
web-node-1 ansible_host=10.100.30.23 ansible_user=debian

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[internal:children]
kibana_host
grafana_host
logging_storage
web_nodes

[internal:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=debian@51.250.94.102 -o ControlMaster=no'
