[bastion]
bastion_host ansible_host=89.169.158.141 ansible_user=debian

[kibana_host]
kibana_server ansible_host=10.100.10.11 ansible_user=debian elastic_target_ip=10.100.20.21

[grafana_host]
grafana_server ansible_host=10.100.10.23 ansible_user=debian postgres_target_ip=10.100.20.21

[logging_storage]
elasticsearch_server ansible_host=10.100.20.21 ansible_user=debian

[web_nodes]
web-node-0 ansible_host=10.100.20.26 ansible_user=debian
web-node-1 ansible_host=10.100.30.11 ansible_user=debian

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_ssh_private_key_file=~/.ssh/id_ed25519

[internal:children]
kibana_host
grafana_host
logging_storage
web_nodes

[internal:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand=\"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_ed25519 -W %h:%p debian@89.169.158.141\" -o ControlMaster=no'
