[bastion]
bastion_host ansible_host=51.250.92.149 ansible_user=debian ansible_ssh_common_args=""

[kibana_host]
kibana_server ansible_host=10.100.10.18 ansible_user=debian elastic_target_ip=10.100.20.18

[grafana_host]
grafana_server ansible_host=10.100.10.21 ansible_user=debian postgres_target_ip=10.100.20.18

[logging_storage]
elasticsearch_server ansible_host=10.100.20.18 ansible_user=debian

[web_nodes]
web-node-0 ansible_host=10.100.20.23 ansible_user=debian
web-node-1 ansible_host=10.100.30.26 ansible_user=debian

[all:vars]
# Фиксируем верный  приватный ключ
ansible_ssh_private_key_file="~/.ssh/id_ed25519"

[internal:children]
kibana_host
grafana_host
logging_storage
web_nodes

[internal:vars]
# Явно передаем путь к ключу внутрь туннеля прыжка, чтобы local-exec в Terraform не зависел от агентов памяти
ansible_ssh_common_args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -l debian 51.250.92.149'"
