---
- name: Deploy Elasticsearch Container s modulem xpack
  hosts: logging_storage
  become: true
  tasks:
    - name: YA stavlyu sistemnye zavisimosti apt dlya Docker
      apt:
        name: apt-transport-https,ca-certificates,curl,gnupg,lsb-release
        state: present
        update_cache: yes

    - name: YA stavlyu sam Docker i plagin compose dlya Debian 13
      apt:
        name: docker.io,docker-compose-v2
        state: present

    - name: YA sozdayu rabochuyu papku dlya Elastic
      file:
        path: /opt/elastic-stack
        state: directory
        mode: '0755'

    - name: YA zapisyvayu konfig docker-compose s moim parolem
      copy:
        dest: /opt/elastic-stack/docker-compose.yml
        mode: '0644'
        content: |
          version: '3.8'
          services:
            elasticsearch:
              image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
              container_name: elasticsearch-storage
              environment:
                - discovery.type=single-node
                - xpack.security.enabled=false
                - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
              volumes:
                - esdata:/usr/share/elasticsearch/data
              ports:
                - "9200:9200"
          volumes:
            esdata:
              driver: local

    - name: YA podnimayu conteiner Elasticseach cherez up
      shell: "docker compose -f /opt/elastic-stack/docker-compose.yml up -d"
