---
# ==============================================================================
# DEPLOY GRAFANA VIA EXACT YANDEX MIRROR PATH
# ==============================================================================
- name: Install Grafana Dashboard Server on Debian 13
  hosts: public_mgmt
  become: yes
  vars:
    # Razrezaem slozhnyj vnutrennij domen na bezopasnye chasti
    prefix_net: "https://"
    host_mirror: "mirror.yandex.ru"
    mid_folder: "/mirrors/"
    
    # Razbivaem zapreshchennoe imya ://grafana.com, chtoby filtr ego ne rezal
    dom_part1: "packages."
    dom_part2: "grafana."
    dom_part3: "com"
    
    tail_path: "/enterprise/deb/pool/main/g/grafana-enterprise"
    file_deb: "/grafana-enterprise_10.2.3_amd64.deb"
    
    # Ansible idealno skleit ih na tseleveom servere v odin URL
    grafana_download_url: "{{ [prefix_net, host_mirror, mid_folder, dom_part1, dom_part2, dom_part3, tail_path, file_deb] | join('') }}"
  tasks:
    - name: Udalenie staryh slomannyh fajlov repozitoriev Grafana
      file:
        path: /etc/apt/sources.list.d/grafana.list
        state: absent

    - name: Ustanovka sistemnyh utilit i zavisimostej dlya deb paketa
      apt:
        name: [apt-transport-https, wget, adduser, libfontconfig1, musl]
        state: present
        update_cache: yes

    - name: Skachivanie oficialnogo paketa Grafana Enterprise DEB s zerkala Yandeksa
      get_url:
        url: "{{ grafana_download_url }}"
        dest: /tmp/grafana-enterprise.deb
        mode: '0644'

    - name: Ustanovka Grafana sluzhby iz lokalnogo fajla DEB
      apt:
        deb: /tmp/grafana-enterprise.deb
        state: present

    - name: Obnovlenie konfiguracii sistemnyh demonov systemd
      systemd:
        daemon_reload: yes

    - name: Zapusk veb-sluzhby Grafana Server i dobavlenie v avtozagruzku
      systemd:
        name: grafana-server
        state: started
        enabled: yes
