[bastion]
bastion_host ansible_host=158.160.53.162 ansible_user=debian

[webservers]
web1 ansible_host=10.0.10.13 ansible_user=debian
web2 ansible_host=10.0.20.17 ansible_user=debian

[logging_storage]
elasticsearch_server ansible_host=10.0.10.20 ansible_user=debian

[prometheus_host]
prometheus_server ansible_host=10.0.10.9 ansible_user=debian

[public_mgmt]
grafana_kibana_server ansible_host=10.0.1.16 ansible_user=debian
